# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./RESTool GUI/Functions/file_functions.h \
    ./RESTool GUI/Functions/licnese_checker.h \
    ./RESTool GUI/Functions/parsers/DefaultBehaveParser.h \
    ./RESTool GUI/Functions/parsers/NWeaponPropertyParser.h \
    ./RESTool GUI/Functions/parsers/ObjectsPropertyParser.h \
    ./RESTool GUI/Functions/parsers/SFXPropertyParser.h \
    ./RESTool GUI/Functions/parsers/SpriteClassParser.h \
    ./RESTool GUI/Functions/parsers/SpriteTypeParser.h \
    ./RESTool GUI/mainwindow.h \
    ./RESTool GUI/resource.h
SOURCES += ./RESTool GUI/Functions/parsers/DefaultBehaveParser.cpp \
    ./RESTool GUI/Functions/parsers/NWeaponPropertyParser.cpp \
    ./RESTool GUI/Functions/parsers/ObjectsPropertyParser.cpp \
    ./RESTool GUI/Functions/parsers/SFXPropertyParser.cpp \
    ./RESTool GUI/Functions/parsers/SpriteClassParser.cpp \
    ./RESTool GUI/Functions/parsers/SpriteTypeParser.cpp \
    ./RESTool GUI/main.cpp \
    ./RESTool GUI/mainwindow.cpp
RESOURCES += qml.qrc
